# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: generated
# Output location is handled in the Dockerfile
output: ''
generate:
  gin-server: true
  models: true
